from __future__ import annotations

from dataclasses import dataclass
from typing import Literal


ReferenceFileFamily = Literal["pdf", "spreadsheet", "document", "text"]
ReferenceFileValidation = Literal[
    "pdf",
    "ooxml-word",
    "ooxml-ppt",
    "ooxml-sheet",
    "odt",
    "compound",
    "rtf",
    "text",
]


@dataclass(frozen=True)
class ReferenceFileType:
    mime_type: str
    family: ReferenceFileFamily
    validation: ReferenceFileValidation
    category: Literal["pdf", "excel", "delimited", "document", "presentation", "text"]
    accepted_mime_types: tuple[str, ...]


_OFFICIAL_MIME_TYPES = {
    "pdf": ("application/pdf",),
    "excel": (
        "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        "application/vnd.ms-excel",
    ),
    "delimited": (
        "text/csv",
        "application/csv",
        "text/tsv",
        "text/x-iif",
        "application/x-iif",
        "application/vnd.google-apps.spreadsheet",
    ),
    "document": (
        "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        "application/msword",
        "application/rtf",
        "text/rtf",
        "application/vnd.oasis.opendocument.text",
        "application/vnd.apple.pages",
        "application/vnd.google-apps.document",
        "application/vnd.apple.iwork",
    ),
    "presentation": (
        "application/vnd.openxmlformats-officedocument.presentationml.presentation",
        "application/vnd.ms-powerpoint",
        "application/vnd.apple.keynote",
        "application/vnd.google-apps.presentation",
        "application/vnd.apple.iwork",
    ),
    "text": (
        "application/javascript",
        "application/typescript",
        "text/xml",
        "text/x-shellscript",
        "text/x-rst",
        "text/x-makefile",
        "text/x-lisp",
        "text/x-asm",
        "text/vbscript",
        "text/css",
        "message/rfc822",
        "application/x-sql",
        "application/x-scala",
        "application/x-rust",
        "application/x-powershell",
        "text/x-diff",
        "text/x-patch",
        "application/x-patch",
        "text/plain",
        "text/markdown",
        "text/x-java",
        "text/x-script.python",
        "text/x-python",
        "text/x-c",
        "text/x-c++",
        "text/x-golang",
        "text/html",
        "text/x-php",
        "application/x-php",
        "application/x-httpd-php",
        "application/x-httpd-php-source",
        "text/x-ruby",
        "text/x-sh",
        "text/x-bash",
        "application/x-bash",
        "text/x-zsh",
        "text/x-tex",
        "text/x-csharp",
        "application/json",
        "text/x-typescript",
        "text/javascript",
        "text/x-go",
        "text/x-rust",
        "text/x-scala",
        "text/x-kotlin",
        "text/x-swift",
        "text/x-lua",
        "text/x-r",
        "text/x-julia",
        "text/x-perl",
        "text/x-objectivec",
        "text/x-objectivec++",
        "text/x-erlang",
        "text/x-elixir",
        "text/x-haskell",
        "text/x-clojure",
        "text/x-groovy",
        "text/x-dart",
        "text/x-awk",
        "application/x-awk",
        "text/jsx",
        "text/tsx",
        "text/x-handlebars",
        "text/x-mustache",
        "text/x-ejs",
        "text/x-jinja2",
        "text/x-liquid",
        "text/x-erb",
        "text/x-twig",
        "text/x-pug",
        "text/x-jade",
        "text/x-tmpl",
        "text/x-cmake",
        "text/x-dockerfile",
        "text/x-gradle",
        "text/x-ini",
        "text/x-properties",
        "text/x-protobuf",
        "application/x-protobuf",
        "text/x-sql",
        "text/x-sass",
        "text/x-scss",
        "text/x-less",
        "text/x-hcl",
        "text/x-terraform",
        "application/x-terraform",
        "text/x-toml",
        "application/x-toml",
        "application/graphql",
        "application/x-graphql",
        "text/x-graphql",
        "application/x-ndjson",
        "application/json5",
        "application/x-json5",
        "text/x-yaml",
        "application/toml",
        "application/x-yaml",
        "application/yaml",
        "text/x-astro",
        "text/srt",
        "application/x-subrip",
        "text/x-subrip",
        "text/vtt",
        "text/x-vcard",
        "text/calendar",
    ),
}


def _policy(
    mime_type: str,
    family: ReferenceFileFamily,
    validation: ReferenceFileValidation,
    category: Literal["pdf", "excel", "delimited", "document", "presentation", "text"],
) -> ReferenceFileType:
    return ReferenceFileType(mime_type, family, validation, category, _OFFICIAL_MIME_TYPES[category])


REFERENCE_FILE_TYPES: dict[str, ReferenceFileType] = {
    ".pdf": _policy("application/pdf", "pdf", "pdf", "pdf"),
    **{
        suffix: _policy("application/vnd.ms-excel", "spreadsheet", "compound", "excel")
        for suffix in (".xla", ".xlb", ".xlc", ".xlm", ".xls", ".xlt", ".xlw")
    },
    ".xlsx": _policy(
        "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        "spreadsheet",
        "ooxml-sheet",
        "excel",
    ),
    ".csv": _policy("text/csv", "spreadsheet", "text", "delimited"),
    ".tsv": _policy("text/tsv", "spreadsheet", "text", "delimited"),
    ".iif": _policy("text/x-iif", "spreadsheet", "text", "delimited"),
    ".doc": _policy("application/msword", "document", "compound", "document"),
    ".docx": _policy(
        "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        "document",
        "ooxml-word",
        "document",
    ),
    ".dot": _policy("application/msword", "document", "compound", "document"),
    ".odt": _policy("application/vnd.oasis.opendocument.text", "document", "odt", "document"),
    ".rtf": _policy("application/rtf", "document", "rtf", "document"),
    **{
        suffix: _policy("application/vnd.ms-powerpoint", "document", "compound", "presentation")
        for suffix in (".pot", ".ppa", ".pps", ".ppt", ".pwz", ".wiz")
    },
    ".pptx": _policy(
        "application/vnd.openxmlformats-officedocument.presentationml.presentation",
        "document",
        "ooxml-ppt",
        "presentation",
    ),
    **{
        suffix: _policy(canonical, "text", "text", "text")
        for suffix, canonical in {
            ".asm": "text/x-asm",
            ".bat": "text/plain",
            ".c": "text/x-c",
            ".cc": "text/x-c++",
            ".conf": "text/plain",
            ".cpp": "text/x-c++",
            ".css": "text/css",
            ".cxx": "text/x-c++",
            ".def": "text/plain",
            ".dic": "text/plain",
            ".eml": "message/rfc822",
            ".h": "text/x-c",
            ".hh": "text/x-c++",
            ".htm": "text/html",
            ".html": "text/html",
            ".ics": "text/calendar",
            ".ifb": "text/calendar",
            ".in": "text/plain",
            ".js": "text/javascript",
            ".json": "application/json",
            ".ksh": "text/x-shellscript",
            ".list": "text/plain",
            ".log": "text/plain",
            ".markdown": "text/markdown",
            ".md": "text/markdown",
            ".mht": "message/rfc822",
            ".mhtml": "message/rfc822",
            ".mime": "message/rfc822",
            ".mjs": "text/javascript",
            ".nws": "message/rfc822",
            ".pl": "text/x-perl",
            ".py": "text/x-python",
            ".rst": "text/x-rst",
            ".s": "text/x-asm",
            ".sql": "text/x-sql",
            ".srt": "text/srt",
            ".text": "text/plain",
            ".txt": "text/plain",
            ".vcf": "text/x-vcard",
            ".vtt": "text/vtt",
            ".xml": "text/xml",
        }.items()
    },
}
